DROP TABLE CLM_ADAPTERDB.CLAIMS_NOTES;

CREATE TABLE CLM_ADAPTERDB.CLAIMS_NOTES
(
  CLAIMNUMBER   VARCHAR2(40 BYTE) NOT NULL,
  POLICY_TYPE   VARCHAR2(50 BYTE) NOT NULL,
  UW_COMPANY    VARCHAR2(50 BYTE)NOT NULL,
  NOTES            CLOB,
  MODEL_TYPE    CHAR(4),
  CLAIM_ML_RESULT_1 VARCHAR(500),
  CLAIM_ML_RESULT_2 VARCHAR(500),
  CLAIM_ML_RESULT_3 VARCHAR(500),  
  INSURED_IS_MAIN_CONTACT CHAR(1)  
  )
LOB (NOTES) STORE AS (
  TABLESPACE  CC_CLM_ADAPTER
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  PCTVERSION  10
  NOCACHE
  LOGGING)
  
TABLESPACE CC_CLM_ADAPTER
     
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX CLM_ADAPTERDB.CLAIMS_NOTES_PK ON CLM_ADAPTERDB.CLAIMS_NOTES
(CLAIMNUMBER)
LOGGING
TABLESPACE CC_CLM_ADAPTER 
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
NOPARALLEL;

--CREATE OR REPLACE PUBLIC SYNONYM CLAIMS_NOTES FOR CLM_ADAPTERDB.CLAIMS_NOTES;








